name: Deploy GitHub Pages

on:
  push:
    branches:
      - my-pages

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Fazer checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Criar os arquivos iniciais e configurar Jekyll
      - name: Configurar arquivos iniciais do site
        run: |
          echo "Criando arquivos iniciais do site..."

          # Criar o arquivo _config.yml
          echo "collections:" > _config.yml
          echo "  mini-books:" >> _config.yml
          echo "    output: true" >> _config.yml

          # Criar o arquivo index.md
          echo "---" > index.md
          echo "title: Bem-vindo ao Guia do Dev Desbravador" >> index.md
          echo "---" >> index.md
          echo "# Bem-vindo ao Guia do Dev Desbravador" >> index.md
          echo "Aqui estão os mini-books disponíveis:" >> index.md
          echo "- [Capítulo 1](mini-books/capitulo-1.md)" >> index.md
          echo "- [Capítulo 2](mini-books/capitulo-2.md)" >> index.md

      # Instalar dependências do Jekyll
      - name: Instalar dependências do Jekyll
        run: |
          echo "Instalando dependências..."
          gem install bundler
          bundle install

      # Gerar o site estático
      - name: Gerar o site estático
        run: |
          echo "Gerando os arquivos do site..."
          bundle exec jekyll build --destination ./site

      # Fazer upload do artefato GitHub Pages
      - name: Fazer upload do artefato GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./site
