      - name: Create my-pages branch, initial Pages files, and pull request
        run: |
          echo "Make sure we are on step 0"
          if [ "$(cat .github/steps/-step.txt)" != 0 ]
          then
            echo "Current step is not 0"
            exit 0
          fi

          echo "Make a branch"
          BRANCH=my-pages
          git checkout -b $BRANCH

          echo "Create config and homepage files"
          touch _config.yml
          printf "%s\n%s\n%s\n\n" "---" "title: Welcome to my blog" "---" > index.md

          echo "Make a commit"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add _config.yml index.md
          git commit --message="Create config and homepages files"

          echo "Push"
          git push --set-upstream origin $BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload the GitHub Pages artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            _config.yml
            index.md
