name: Step 5, Merge your pull request
# This step triggers after a pull requst is merged to `main`.
# This workflow updates from step 5 to step X.

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: get_step
        name: Read step file and set output
        run: |
          STEP_FILE_PATH="./.github/steps/-step.txt" # Confirme se este é o caminho correto
          if [ -f "$STEP_FILE_PATH" ]; then
            # Lê o conteúdo do arquivo, remove quaisquer caracteres de nova linha (\n) ou retorno de carro (\r)
            STEP_VALUE=$(cat "$STEP_FILE_PATH" | tr -d '\n\r')
            echo "Valor lido do arquivo de passo (após limpeza): '${STEP_VALUE}'" # Para debug
            echo "current_step=${STEP_VALUE}" >> $GITHUB_OUTPUT
          else
            echo "Arquivo de passo não encontrado em $STEP_FILE_PATH" # Para debug
            echo "current_step=" >> $GITHUB_OUTPUT # Define como vazio se não encontrado
          fi

  on_merge:
    name: On merge
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == '5' }} # Comparar como string
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update to step X
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: '5' # Como string
          to_step: 'X'   # Como string
          # ATENÇÃO: Se o seu curso atualiza o README na branch 'main',
          # esta branch_name deveria ser 'main'.
          # Se 'my-pages' foi usada durante o curso e agora tudo está na 'main',
          # e o README da 'main' é o que importa, ajuste para 'main'.
          branch_name: my-pages
